### ISSUE TITLE
Are the docs still being completed?

### ISSUE THREAD

**Issue by SvenBudak** [MarcusCemes/image-processing-pipeline#30]
Currently I am not able to understand how to use this package. I can't find any hints in the documentation for almost any question that comes up. 

I've been trying for 2 hours, just for a folder that contains the following:

```
mobile.jpg (1200x1200)
tablet.jpg (1920x823)
desktop.jpg (2400x1028)
```

convert to (with exactly these filenames):

```
mobile.jpg (600x600)
mobile_2x.jpg (1200x1200)
tablet.jpg (960x411)
tablet_2x.jpg (1920x823)
desktop.jpg (2400x1028)
desktop_2x.jpg (1200x514)
```

My last attempt looked like this:

input: src/assets/img
output: img-dist

```
pipeline:
  - pipe: resize
    options:
      breakpoints:
        - name: 1x
          resizeOptions:
            width: 600
        - name: 2x
          resizeOptions:
            width: 1200
        - name: 1x
          resizeOptions:
            width: 960
        - name: 2x
          resizeOptions:
            width: 1920
        - name: 1x
          resizeOptions:
            width: 1200
        - name: 2x
          resizeOptions:
            width: 2400
    save: "[name]-[breakpoint][ext]"
```

But this way, of course, it generates 6 variants of each image, instead of what I need (described above).
