### ISSUE TITLE
IPP just ignores some breakpoints

### ISSUE THREAD

**Issue by axel-verse** [MarcusCemes/image-processing-pipeline#31]
**Describe the bug**
IPP ignores breakpoints specified in `.ipprc.yml`

**Steps to reproduce**
Got 12 webp files in src directory

.ipprc.yml
```yml
input: src
output: out

manifest:
  source:
    p: path
    h: "hash:6"
  format:
    w: width
    p: path
    h: "hash:6"
    
pipeline:
  - pipe: resize
    options:
      breakpoints:
        - name: xs
          resizeOptions:
            width: 640
            height: 400
        - name: sm
          resizeOptions:
            width: 768
            height: 400
        - name: md
          resizeOptions:
            width: 1024
            height: 400
        - name: lg
          resizeOptions:
            width: 1280
            height: 400
        - name: xl
          resizeOptions:
            width: 1536
            height: 400
        - name: 2xl
          resizeOptions:
            width: 1920
            height: 400
        - name: 3xl
          resizeOptions:
            width: 1920
            height: 1080
    save: "[breakpoint]-[name].[hash:6][ext]"
```

What I've done

```bash
yarn global add @ipp/cli
ipp
ls out

3xl-slide10.9fe774.webp  3xl-slide1.95fadd.webp  3xl-slide4.d87084.webp  3xl-slide7.f12bff.webp  manifest.json          sm-slide4.c23f93.webp   xs-slide12.d92319.webp  xs-slide3.84914e.webp  xs-slide6.674dba.webp  xs-slide9.8590e2.webp
3xl-slide11.5f3294.webp  3xl-slide2.0689f0.webp  3xl-slide5.7f4910.webp  3xl-slide8.7d6901.webp  sm-slide2.456f41.webp  xs-slide10.11aaf5.webp  xs-slide1.9a7695.webp   xs-slide4.ca79f4.webp  xs-slide7.810229.webp
3xl-slide12.6c1a0e.webp  3xl-slide3.d7bc8b.webp  3xl-slide6.9505a2.webp  3xl-slide9.49105f.webp  sm-slide3.f13384.webp  xs-slide11.a1129e.webp  xs-slide2.d3c56d.webp   xs-slide5.322bb9.webp  xs-slide8.f98ee7.webp    
```

**Expected behaviour**
Each file should be processed for every breakpoint

**System information:**

- OS: Manjaro Linux 21.1.2
- Node version: 16.8.0
- IPP version: cli 1.2.2

**Comment by MarcusCemes** [comment]
Hi,

Are all the source image dimensions larger than the largest breakpoint you specified (1920x1080)? If yes, then I will need some more information to reproduce the bug, a sandbox reproduction would be ideal. If not, read on.

One of my objectives with IPP was to avoid any duplicate output images with the same dimensions to eliminate any unnecessary network requests and caching. In order to achieve this, by default, IPP will pass `withoutEnlargement: true` to sharp (image manipulation library) and filter the list of breakpoints, comparing each against the source image dimensions to ensure that only one image of a certain size would be exported.

For example, if you would give it an image of 64x64, and specify two breakpoints at 128x128 and 256x256, both breakpoints would be constrained to 64x64 to prevent image enlargement, therefore only one breakpoint would be exported (which one depends on the order in which you specify them, the final resulting image would only be 64x64 to prevent lossy upscaling).

This is where the `manifest.json` file or the webpack loader comes in handy, it lets the client check what variants are available.

You can **opt-out** of this behaviour by passing `allowDuplicates: true` to the resize pipe. This will not check for duplicate exported sizes and will not pass `withoutEnlargement: true` to sharp, although you can set this manually for each breakpoint individually. It's not currently documented (actually, not much is), I haven't got much time for open-source at the moment, but I can try and help by answering any questions.

Good luck!

```yaml
options:
  allowDuplicates: true
  breakpoints:
    - name: xs
```

https://github.com/MarcusCemes/image-processing-pipeline/blob/e764b694ce10da0a6b102cfeb29692af25182cb2/packages/core/src/pipes/resize.ts#L22
